name: SkCord
version: '3.0-RELEASE'
api-version: 1.21
main: net.fedustria.skcord.SkCord
depend: [ Skript ]
authors: [ Fedox, Austria7 ]
description: Send discord webhooks with Skript!
commands:
  skcord: